name: Runs News scrapper

on:
  push:
  schedule:
    - cron: "20 04,09,12 * * *" # (UTC) 4:20 AM & 9:20 AM -> (NEP) 10:00 AM & 03:05 PM

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - run: npm install
      - name: Run script
        run: npm start
      - name: Setup Git Config
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Remove all files except __daily_news
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name '__daily_news' ! -name '.git' ! -name 'Readme.md' -exec rm -rf {} +
      - name: Commit changes if any
        run: |
          git add .
          git commit -m "Update repository with __daily_news content" || echo "No changes to commit"
      - name: Push changes to another repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          repository: bibhuticoder/nepali-news-api
          branch: main
          force: true