name: Runs News scrapper

on:
  push:
  schedule:
    - cron: "20 04,09,12 * * *" # (UTC) 4:20 AM & 9:20 AM -> (NEP) 10:00 AM & 03:05 PM

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - run: npm install
      - name: Run script
        run: npm start
      - name: Setup Git Config
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Clear existing files and add new content
        run: |
          git rm -r --cached .  # Remove all files from the index (staging area)
          git clean -fdx  # Remove all untracked files and directories
          git add __daily_news/*  # Add only the __daily_news folder
          git commit -m "Update __daily_news folder" || echo "No changes to commit"
      - name: Push changes to another repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          repository: bibhuticoder/nepali-news-api
          branch: main
          force: true