name: Runs News scrapper

on:
  push:
  schedule:
    - cron: "20 04,09,12 * * *" # (UTC) 4:20 AM & 9:20 AM -> (NEP) 10:00 AM & 03:05 PM

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - run: npm install
      - name: Run script
        run: npm start
      - name: Setup Git Config
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Remove all except __daily_news folder
        run: |
          shopt -s extglob
          git rm -r --cached !(.__daily_news)  # Remove all files except __daily_news from the index
          git clean -fdx --exclude=__daily_news/  # Clean untracked files except __daily_news
      - name: Add __daily_news folder and commit changes
        run: |
          git add ./__daily_news/*
          git commit -m "Update __daily_news folder" || echo "No changes to commit"
      - name: Push changes to another repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          repository: bibhuticoder/nepali-news-api
          branch: main
          force: true